### ISSUE TITLE
Missing Django 2.x support

### ISSUE THREAD

**Issue by nerdoc** [nshafer/django-brunch#2]
Just wanted to download this plugin and I saw that the dependency is django<=2.0.0 - is there a chance that it will get updated?

**Comment by nerdoc** [comment]
According to [Stackexchange](https://stackoverflow.com/questions/48392267/why-is-this-popen-call-returning-a-io-unsupportedoperation-fileno-error-in-dj), you could simply use the `._out` attr of the stdin/stdout objects, and it seems to work perfectly (tried it with Django 2.1.2):

```py
brunch_process = subprocess.Popen(cmd, cwd=settings.BRUNCH_DIR, shell=settings.BRUNCH_SHELL,
        stdin=subprocess.PIPE, 
        stdout=self.stdout._out, # <== here...
        stderr=self.stderr._out)  # <== and here
```

**Comment by nshafer** [comment]
Just pushed version 1.0.3 with updates for django 2.0, 2.1. I decided to just use `sys.stdout` and `sys.stderr` as I don't need the `OutputWrapper` functionality from `BaseCommand` at all. Thanks for letting me know it was failing.

**Comment by nerdoc** [comment]
Works, thanks.
