### ISSUE TITLE
Django 2.2 Support

### ISSUE THREAD

**Issue by kavdev** [nshafer/django-brunch#3]
Hi there!

django-brunch seems to be working fine in django 2.2. I didn't see any automated tests; can you check compatibility however you usually do and then update [the dependency check](https://github.com/nshafer/django-brunch/blob/master/setup.py#L35)?

Thanks!

``django-brunch 1.0.3 has requirement Django<2.2.0,>=1.11.0, but you'll have django 2.2.1 which is incompatible.``

**Comment by nshafer** [comment]
Removed the version constraint after manually testing it works fine with Django 2.2, both with StatReloader and WatchmanReloader. Version 1.0.4 is live on pypi.

**Comment by kavdev** [comment]
Thanks @nshafer!
